[phases.setup]
nixPkgs = ["nodejs_18", "chromium"]

[phases.install]
cmd = "cd backend && npm ci"

[phases.build]
cmd = "echo 'Build complete - backend ready'"

[start]
cmd = "cd backend && npm run start:production"
