[phases.setup]
nixPkgs = [
  "nodejs_20", 
  "chromium",
  "xvfb-run",
  "fontconfig",
  "freetype",
  "harfbuzz",
  "cacert",
  "liberation_ttf",
  "nss",
  "glib",
  "gtk3",
  "alsa-lib",
  "at-spi2-atk",
  "cups",
  "dbus",
  "expat",
  "libdrm",
  "libxkbcommon",
  "mesa"
]

[phases.install]
cmd = "cd backend && npm ci --omit=dev"

[phases.build]
cmd = "echo 'Backend deployment ready'"

[start]
cmd = "cd backend && npm run start:production"
